import os
import multiprocessing

# App
APP_NAME = 'system-monitor'
WORKERS_NUM = multiprocessing.cpu_count()
DEFAULT_TARGET = "unix://var/run/docker.sock"
WORKER_HEARTBEAT_HZ = 2
APP_HEARTBEAT_HZ = 5
LOG_VERSION = 1

# Jobs
JOB_FETCH_CONTAINER_LIST = True
JOB_FETCH_CONTAINER_STATS = False
JOB_FETCH_CONTAINER_TOP = True
JOB_FETCH_CONTAINER_CONFIG = True
JOB_FETCH_DEVICE_HEALTH = True
JOB_FETCH_DEVICE_RESOURCES_STATS = True
JOB_FETCH_ENDPOINT_INFO = True
JOB_PUSH_TO_SERVER = True

# Docker
DEFAULT_DOCKER_TCP_PORT = 2375

# Job: Device Health
DEFAULT_DEVICE_HEALTH_API_PORT = 8085
FETCH_NEW_DEVICE_STATS_EVERY_S = 10

# Job: Device Resources
FETCH_NEW_DEVICE_RESOURCES_STATS_EVERY_S = 5

# Job: Containers List
FETCH_NEW_CONTAINERS_EVERY_S = 10

# Job: Container Stats
FETCH_NEW_CONTAINER_STATS_EVERY_S = 10

# Job: Process Stats
FETCH_NEW_PROCESS_STATS_EVERY_S = 5

# Job: Printer
VERBOSE_PRINT_STATUS_EVERY_S = 2

# Job: Publisher
LOG_API_PROTOCOL = os.environ.get('LOG_API_PROTOCOL', 'https')
LOG_API_HOSTNAME = os.environ.get('LOG_API_HOSTNAME', 'dashboard.duckietown.org')
LOG_API_VERSION = os.environ.get('LOG_API_VERSION', '1.0')
LOG_API_URL = "{:s}://{:s}/web-api/{}/data/set/json".format(
    LOG_API_PROTOCOL,
    LOG_API_HOSTNAME,
    LOG_API_VERSION
)
LOG_API_DEFAULT_DATABASE = 'db_log_default'
LOG_DEFAULT_GROUP = 'default'
LOG_API_RETRY_EVERY_S = 5
LOG_API_RETRY_N_TIMES = 3
LOG_API_REQUEST_TIMEOUT_S = 20
